version: '3.4'

services:
  educator.api:
    image: ${DOCKER_REGISTRY-}educatorapi
    container_name: educator.api
    build:
      context: .
      dockerfile: Educator.Api/Dockerfile
    volumes:
      - ./certificates:/root/.aspnet/https/
      - ${APPDATA}/microsoft/UserSecrets:/root/.microsoft/usersecrets
    ports:
      - "8080:80"
      - "8081:443"
    environment:
        ASPNETCORE_URLS: "https://+;http://+"
        ASPNETCORE_HTTPS_PORT: "8081"
        ASPNETCORE_ENVIRONMENT: "Development"
        ASPNETCORE_Kestrel__Certificates__Default__Password: 321321
        ASPNETCORE_Kestrel__Certificates__Default__Path: "/root/.aspnet/https/Educator.Api.pfx"

